global using Microsoft.UI;
global using Microsoft.UI.Xaml;
global using Microsoft.UI.Xaml.Controls;
global using Microsoft.UI.Xaml.Navigation;
global using WinUICommunity;
global using CommunityToolkit.Mvvm.ComponentModel;
global using CommunityToolkit.Mvvm.Input;
global using Microsoft.Extensions.DependencyInjection;
global using $safeprojectname$.Views;
global using $safeprojectname$.Common;
global using $safeprojectname$.ViewModels;$ExtraGlobalUsing$
